// <auto-generated />
using System;
using System.Net;
using Infrastructure.Postgres.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Postgres.Persistence.Migrations
{
    [DbContext(typeof(HanLexiconDbContext))]
    [Migration("20260427050526_AddReviewHistory")]
    partial class AddReviewHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HanLexicon.Domain.Entities.ChallengeWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ExampleVn")
                        .HasColumnType("text")
                        .HasColumnName("example_vn");

                    b.Property<string>("ExampleZh")
                        .HasColumnType("text")
                        .HasColumnName("example_zh");

                    b.Property<string>("Hanzi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hanzi");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("MeaningVn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning_vn");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pinyin");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("challenge_words_pkey");

                    b.HasIndex(new[] { "LessonId", "SortOrder" }, "idx_challenge_words_lesson");

                    b.ToTable("challenge_words", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("doc_type")
                        .HasDefaultValueSql("'pdf'::character varying");

                    b.Property<string>("DownloadUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("download_url");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("documents_pkey");

                    b.HasIndex(new[] { "CategoryId" }, "idx_docs_category");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.HanziCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("character");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Mnemonic")
                        .HasColumnType("text")
                        .HasColumnName("mnemonic");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pinyin");

                    b.Property<string>("Radical")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("radical");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<short?>("StrokeCount")
                        .HasColumnType("smallint")
                        .HasColumnName("stroke_count");

                    b.HasKey("Id")
                        .HasName("hanzi_cards_pkey");

                    b.HasIndex(new[] { "LessonId", "SortOrder" }, "idx_hanzi_lesson");

                    b.ToTable("hanzi_cards", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<short?>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorLog")
                        .HasColumnType("jsonb")
                        .HasColumnName("error_log");

                    b.Property<int>("FailedRows")
                        .HasColumnType("integer")
                        .HasColumnName("failed_rows");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProcessedRows")
                        .HasColumnType("integer")
                        .HasColumnName("processed_rows");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'::character varying");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer")
                        .HasColumnName("total_rows");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("import_jobs_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Badge")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("badge");

                    b.Property<short>("CategoryId")
                        .HasColumnType("smallint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("filename")
                        .HasComment("T�n file HTML g?c, d�ng l�m game_id khi luu ti?n d?");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icon")
                        .HasDefaultValueSql("'??'::character varying");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_published");

                    b.Property<short?>("LessonNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("lesson_number");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<string>("TitleCn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title_cn");

                    b.Property<string>("TitleVn")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title_vn");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("lessons_pkey");

                    b.HasIndex(new[] { "CategoryId" }, "idx_lessons_category");

                    b.HasIndex(new[] { "Filename" }, "idx_lessons_filename");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.LessonCategory", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("slug");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("lesson_categories_pkey");

                    b.HasIndex(new[] { "Slug" }, "lesson_categories_slug_key")
                        .IsUnique();

                    b.ToTable("lesson_categories", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.MediaFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("CdnUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cdn_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<int?>("FileSizeKb")
                        .HasColumnType("integer")
                        .HasColumnName("file_size_kb");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("media_type");

                    b.Property<string>("MimeType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mime_type");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("OwnerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("owner_type");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id")
                        .HasName("media_files_pkey");

                    b.HasIndex("UploadedBy");

                    b.HasIndex(new[] { "OwnerType", "OwnerId" }, "idx_media_owner");

                    b.ToTable("media_files", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Permission", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("permissions_pkey");

                    b.HasIndex(new[] { "Code" }, "permissions_code_key")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.QuizOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_text");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("quiz_options_pkey");

                    b.HasIndex(new[] { "QuestionId", "SortOrder" }, "idx_quiz_options_question");

                    b.ToTable("quiz_options", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<short>("Difficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("difficulty");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("quiz_questions_pkey");

                    b.HasIndex(new[] { "LessonId", "SortOrder" }, "idx_quiz_lesson");

                    b.ToTable("quiz_questions", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Radical", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ExampleChars")
                        .HasColumnType("text")
                        .HasColumnName("example_chars");

                    b.Property<string>("Meaning")
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<string>("Radical1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("radical");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("radicals_pkey");

                    b.HasIndex("SetId");

                    b.ToTable("radicals", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.RadicalSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icon")
                        .HasDefaultValueSql("'??'::character varying");

                    b.Property<Guid?>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<short>("SetNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("set_number");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("radical_sets_pkey");

                    b.HasIndex("LessonId");

                    b.HasIndex(new[] { "SetNumber" }, "radical_sets_set_number_key")
                        .IsUnique();

                    b.ToTable("radical_sets", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.ReviewHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<short>("CorrectCount")
                        .HasColumnType("smallint")
                        .HasColumnName("correct_count");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("details_json");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<short>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("score");

                    b.Property<short>("TotalQuestions")
                        .HasColumnType("smallint")
                        .HasColumnName("total_questions");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("review_history_pkey");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("review_history", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Role", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("roles_pkey");

                    b.HasIndex(new[] { "Code" }, "roles_code_key")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.SearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("query");

                    b.Property<DateTime>("SearchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("searched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("VocabId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocab_id");

                    b.HasKey("Id")
                        .HasName("search_history_pkey");

                    b.HasIndex("VocabId");

                    b.HasIndex(new[] { "UserId", "SearchedAt" }, "idx_search_user")
                        .IsDescending(false, true);

                    b.ToTable("search_history", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.SystemLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Exception")
                        .HasColumnType("text")
                        .HasColumnName("exception");

                    b.Property<string>("LogLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("log_level");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RequestMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("request_path");

                    b.Property<string>("TraceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trace_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("system_logs_pkey");

                    b.ToTable("system_logs", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash")
                        .HasComment("bcrypt hash, cost=12");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "users_username_key")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("T�i kho?n h?c vi�n v� qu?n tr? vi�n");
                        });
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.UserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<short>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("attempts");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean")
                        .HasColumnName("completed");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("CurrentIndex")
                        .HasColumnType("integer")
                        .HasColumnName("current_index");

                    b.Property<DateTime>("LastPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_played")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<short>("Score")
                        .HasColumnType("smallint")
                        .HasColumnName("score");

                    b.Property<int>("TimeSpentS")
                        .HasColumnType("integer")
                        .HasColumnName("time_spent_s");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_progress_pkey");

                    b.HasIndex(new[] { "UserId", "Completed" }, "idx_progress_completed");

                    b.HasIndex(new[] { "LessonId" }, "idx_progress_lesson");

                    b.HasIndex(new[] { "UserId" }, "idx_progress_user");

                    b.HasIndex(new[] { "UserId", "LessonId" }, "user_progress_user_id_lesson_id_key")
                        .IsUnique();

                    b.ToTable("user_progress", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "RoleId")
                        .HasName("user_roles_pkey");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "UserId" }, "idx_user_roles_user");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_sessions_pkey");

                    b.HasIndex(new[] { "ExpiresAt" }, "idx_sessions_expires");

                    b.HasIndex(new[] { "RefreshToken" }, "idx_sessions_token");

                    b.HasIndex(new[] { "UserId" }, "idx_sessions_user");

                    b.HasIndex(new[] { "RefreshToken" }, "user_sessions_refresh_token_key")
                        .IsUnique();

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.UserWordProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("VocabId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocab_id");

                    b.Property<DateTime>("LastReviewed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_reviewed")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ReviewCount")
                        .HasColumnType("smallint")
                        .HasColumnName("review_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'learning'::character varying");

                    b.HasKey("UserId", "VocabId")
                        .HasName("user_word_progress_pkey");

                    b.HasIndex("VocabId");

                    b.ToTable("user_word_progress", null, t =>
                        {
                            t.HasComment("Luu l?ch s? h?c t?p/tra c?u c?a t?ng t? v?ng ri�ng bi?t");
                        });
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.VLessonsSummary", b =>
                {
                    b.Property<string>("Badge")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("badge");

                    b.Property<string>("Category")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("Filename")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("filename");

                    b.Property<long?>("HanziCount")
                        .HasColumnType("bigint")
                        .HasColumnName("hanzi_count");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("icon");

                    b.Property<Guid?>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short?>("LessonNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("lesson_number");

                    b.Property<long?>("QuizCount")
                        .HasColumnType("bigint")
                        .HasColumnName("quiz_count");

                    b.Property<string>("TitleCn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title_cn");

                    b.Property<string>("TitleVn")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title_vn");

                    b.Property<long?>("VocabCount")
                        .HasColumnType("bigint")
                        .HasColumnName("vocab_count");

                    b.ToTable((string)null);

                    b.ToView("v_lessons_summary", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.VUserStat", b =>
                {
                    b.Property<decimal?>("AvgScore")
                        .HasColumnType("numeric")
                        .HasColumnName("avg_score");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<long?>("LessonsCompleted")
                        .HasColumnType("bigint")
                        .HasColumnName("lessons_completed");

                    b.Property<long?>("LessonsStarted")
                        .HasColumnType("bigint")
                        .HasColumnName("lessons_started");

                    b.Property<long?>("TotalTimeSeconds")
                        .HasColumnType("bigint")
                        .HasColumnName("total_time_seconds");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.ToTable((string)null);

                    b.ToView("v_user_stats", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Vocabulary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text")
                        .HasColumnName("audio_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ExampleCn")
                        .HasColumnType("text")
                        .HasColumnName("example_cn");

                    b.Property<string>("ExamplePy")
                        .HasColumnType("text")
                        .HasColumnName("example_py");

                    b.Property<string>("ExampleVn")
                        .HasColumnType("text")
                        .HasColumnName("example_vn");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("MeaningEn")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("meaning_en");

                    b.Property<string>("Pinyin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pinyin");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("word");

                    b.HasKey("Id")
                        .HasName("vocabulary_pkey");

                    b.HasIndex(new[] { "LessonId", "SortOrder" }, "idx_vocab_lesson");

                    b.ToTable("vocabulary", (string)null);
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<short>("PermissionId")
                        .HasColumnType("smallint")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("role_permissions_pkey");

                    b.HasIndex("PermissionId");

                    b.HasIndex(new[] { "RoleId" }, "idx_role_permissions_role");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.ChallengeWord", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.Lesson", "Lesson")
                        .WithMany("ChallengeWords")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("challenge_words_lesson_id_fkey");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Document", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.LessonCategory", "Category")
                        .WithMany("Documents")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("documents_category_id_fkey");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.HanziCard", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.Lesson", "Lesson")
                        .WithMany("HanziCards")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hanzi_cards_lesson_id_fkey");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.ImportJob", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.LessonCategory", "Category")
                        .WithMany("ImportJobs")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("import_jobs_category_id_fkey");

                    b.HasOne("HanLexicon.Domain.Entities.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("HanLexicon.Domain.Entities.User", "UploadedByNavigation")
                        .WithMany("ImportJobs")
                        .HasForeignKey("UploadedBy")
                        .IsRequired()
                        .HasConstraintName("import_jobs_uploaded_by_fkey");

                    b.Navigation("Category");

                    b.Navigation("Lesson");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Lesson", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.LessonCategory", "Category")
                        .WithMany("Lessons")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("lessons_category_id_fkey");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.MediaFile", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.User", "UploadedByNavigation")
                        .WithMany("MediaFiles")
                        .HasForeignKey("UploadedBy")
                        .HasConstraintName("media_files_uploaded_by_fkey");

                    b.Navigation("UploadedByNavigation");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.QuizOption", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.QuizQuestion", "Question")
                        .WithMany("QuizOptions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("quiz_options_question_id_fkey");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.QuizQuestion", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.Lesson", "Lesson")
                        .WithMany("QuizQuestions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("quiz_questions_lesson_id_fkey");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Radical", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.RadicalSet", "Set")
                        .WithMany("Radicals")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("radicals_set_id_fkey");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.RadicalSet", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.Lesson", "Lesson")
                        .WithMany("RadicalSets")
                        .HasForeignKey("LessonId")
                        .HasConstraintName("radical_sets_lesson_id_fkey");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.ReviewHistory", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.Lesson", "Lesson")
                        .WithMany("ReviewHistories")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("review_history_lesson_id_fkey");

                    b.HasOne("HanLexicon.Domain.Entities.User", "User")
                        .WithMany("ReviewHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("review_history_user_id_fkey");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.SearchHistory", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.User", "User")
                        .WithMany("SearchHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("search_history_user_id_fkey");

                    b.HasOne("HanLexicon.Domain.Entities.Vocabulary", "Vocab")
                        .WithMany("SearchHistories")
                        .HasForeignKey("VocabId")
                        .HasConstraintName("search_history_vocab_id_fkey");

                    b.Navigation("User");

                    b.Navigation("Vocab");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.UserProgress", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.Lesson", "Lesson")
                        .WithMany("UserProgresses")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_progress_lesson_id_fkey");

                    b.HasOne("HanLexicon.Domain.Entities.User", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_progress_user_id_fkey");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_role_id_fkey");

                    b.HasOne("HanLexicon.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_user_id_fkey");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.UserSession", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_sessions_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.UserWordProgress", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.User", "User")
                        .WithMany("UserWordProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_word_progress_user_id_fkey");

                    b.HasOne("HanLexicon.Domain.Entities.Vocabulary", "Vocab")
                        .WithMany("UserWordProgresses")
                        .HasForeignKey("VocabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_word_progress_vocab_id_fkey");

                    b.Navigation("User");

                    b.Navigation("Vocab");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Vocabulary", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.Lesson", "Lesson")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("vocabulary_lesson_id_fkey");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RolePermission", b =>
                {
                    b.HasOne("HanLexicon.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_permission_id_fkey");

                    b.HasOne("HanLexicon.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("role_permissions_role_id_fkey");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Lesson", b =>
                {
                    b.Navigation("ChallengeWords");

                    b.Navigation("HanziCards");

                    b.Navigation("QuizQuestions");

                    b.Navigation("RadicalSets");

                    b.Navigation("ReviewHistories");

                    b.Navigation("UserProgresses");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.LessonCategory", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("ImportJobs");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.QuizQuestion", b =>
                {
                    b.Navigation("QuizOptions");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.RadicalSet", b =>
                {
                    b.Navigation("Radicals");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.User", b =>
                {
                    b.Navigation("ImportJobs");

                    b.Navigation("MediaFiles");

                    b.Navigation("ReviewHistories");

                    b.Navigation("SearchHistories");

                    b.Navigation("UserProgresses");

                    b.Navigation("UserRoles");

                    b.Navigation("UserSessions");

                    b.Navigation("UserWordProgresses");
                });

            modelBuilder.Entity("HanLexicon.Domain.Entities.Vocabulary", b =>
                {
                    b.Navigation("SearchHistories");

                    b.Navigation("UserWordProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
