CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE lesson_categories (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    slug character varying(30) NOT NULL,
    name character varying(80) NOT NULL,
    sort_order smallint NOT NULL,
    CONSTRAINT lesson_categories_pkey PRIMARY KEY (id)
);

CREATE TABLE permissions (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    CONSTRAINT permissions_pkey PRIMARY KEY (id)
);

CREATE TABLE roles (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    code character varying(50) NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    CONSTRAINT roles_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    username character varying(50) NOT NULL,
    password_hash text NOT NULL,
    display_name character varying(100),
    email character varying(150),
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    last_login_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);
COMMENT ON TABLE users IS 'T�i kho?n h?c vi�n v� qu?n tr? vi�n';
COMMENT ON COLUMN users.password_hash IS 'bcrypt hash, cost=12';

CREATE TABLE documents (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    category_id smallint NOT NULL,
    title text NOT NULL,
    description text,
    download_url text NOT NULL,
    doc_type character varying(30) NOT NULL DEFAULT ('pdf'::character varying),
    sort_order smallint NOT NULL,
    is_published boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT documents_pkey PRIMARY KEY (id),
    CONSTRAINT documents_category_id_fkey FOREIGN KEY (category_id) REFERENCES lesson_categories (id)
);

CREATE TABLE lessons (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    category_id smallint NOT NULL,
    lesson_number smallint,
    filename character varying(120) NOT NULL,
    title_cn character varying(200),
    title_vn character varying(500),
    icon character varying(10) NOT NULL DEFAULT ('??'::character varying),
    description character varying(200),
    badge character varying(20),
    is_published boolean NOT NULL DEFAULT TRUE,
    sort_order smallint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    updated_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT lessons_pkey PRIMARY KEY (id),
    CONSTRAINT lessons_category_id_fkey FOREIGN KEY (category_id) REFERENCES lesson_categories (id)
);
COMMENT ON COLUMN lessons.filename IS 'T�n file HTML g?c, d�ng l�m game_id khi luu ti?n d?';

CREATE TABLE role_permissions (
    role_id smallint NOT NULL,
    permission_id smallint NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
    CONSTRAINT role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE,
    CONSTRAINT role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
);

CREATE TABLE import_jobs (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    uploaded_by uuid NOT NULL,
    file_name character varying(255) NOT NULL,
    status character varying(20) NOT NULL DEFAULT ('pending'::character varying),
    total_rows integer NOT NULL,
    processed_rows integer NOT NULL,
    failed_rows integer NOT NULL,
    error_log jsonb,
    category_id smallint,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT import_jobs_pkey PRIMARY KEY (id),
    CONSTRAINT import_jobs_category_id_fkey FOREIGN KEY (category_id) REFERENCES lesson_categories (id),
    CONSTRAINT import_jobs_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users (id)
);

CREATE TABLE media_files (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    owner_type character varying(30) NOT NULL,
    owner_id uuid NOT NULL,
    media_type character varying(10) NOT NULL,
    file_name character varying(255) NOT NULL,
    storage_key text NOT NULL,
    cdn_url text NOT NULL,
    mime_type character varying(50),
    file_size_kb integer,
    uploaded_by uuid,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT media_files_pkey PRIMARY KEY (id),
    CONSTRAINT media_files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES users (id)
);

CREATE TABLE media_folders (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    name character varying(100) NOT NULL,
    description text,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT media_folders_pkey PRIMARY KEY (id)
);

CREATE TABLE user_roles (
    user_id uuid NOT NULL,
    role_id smallint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE user_sessions (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    user_id uuid NOT NULL,
    refresh_token text NOT NULL,
    ip_address inet,
    user_agent text,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
    CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE challenge_words (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    lesson_id uuid NOT NULL,
    sort_order smallint NOT NULL,
    hanzi character varying(50) NOT NULL,
    pinyin character varying(100) NOT NULL,
    meaning_vn text NOT NULL,
    example_zh text,
    example_vn text,
    CONSTRAINT challenge_words_pkey PRIMARY KEY (id),
    CONSTRAINT challenge_words_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE
);

CREATE TABLE hanzi_cards (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    lesson_id uuid NOT NULL,
    sort_order smallint NOT NULL,
    character character varying(10) NOT NULL,
    pinyin character varying(50) NOT NULL,
    meaning text NOT NULL,
    mnemonic text,
    stroke_count smallint,
    radical character varying(10),
    CONSTRAINT hanzi_cards_pkey PRIMARY KEY (id),
    CONSTRAINT hanzi_cards_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE
);

CREATE TABLE quiz_questions (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    lesson_id uuid NOT NULL,
    sort_order smallint NOT NULL,
    question text NOT NULL,
    explanation text NOT NULL,
    difficulty smallint NOT NULL DEFAULT 1,
    CONSTRAINT quiz_questions_pkey PRIMARY KEY (id),
    CONSTRAINT quiz_questions_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE
);

CREATE TABLE radical_sets (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    set_number smallint NOT NULL,
    title character varying(100) NOT NULL,
    icon character varying(10) NOT NULL DEFAULT ('??'::character varying),
    lesson_id uuid,
    CONSTRAINT radical_sets_pkey PRIMARY KEY (id),
    CONSTRAINT radical_sets_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES lessons (id)
);

CREATE TABLE user_progress (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    user_id uuid NOT NULL,
    lesson_id uuid NOT NULL,
    score smallint NOT NULL,
    completed boolean NOT NULL,
    attempts smallint NOT NULL DEFAULT 1,
    time_spent_s integer NOT NULL,
    last_played timestamp with time zone NOT NULL DEFAULT (now()),
    created_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT user_progress_pkey PRIMARY KEY (id),
    CONSTRAINT user_progress_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE,
    CONSTRAINT user_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE vocabulary (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    lesson_id uuid NOT NULL,
    sort_order smallint NOT NULL,
    word character varying(50) NOT NULL,
    pinyin character varying(100) NOT NULL,
    meaning text NOT NULL,
    "MeaningEn" text,
    "AudioUrl" text,
    "ImageUrl" text,
    "ExampleCn" text,
    "ExamplePy" text,
    "ExampleVn" text,
    CONSTRAINT vocabulary_pkey PRIMARY KEY (id),
    CONSTRAINT vocabulary_lesson_id_fkey FOREIGN KEY (lesson_id) REFERENCES lessons (id) ON DELETE CASCADE
);

CREATE TABLE quiz_options (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    question_id uuid NOT NULL,
    sort_order smallint NOT NULL,
    option_text text NOT NULL,
    is_correct boolean NOT NULL,
    CONSTRAINT quiz_options_pkey PRIMARY KEY (id),
    CONSTRAINT quiz_options_question_id_fkey FOREIGN KEY (question_id) REFERENCES quiz_questions (id) ON DELETE CASCADE
);

CREATE TABLE radicals (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    set_id uuid NOT NULL,
    sort_order smallint NOT NULL,
    radical character varying(10) NOT NULL,
    name character varying(50) NOT NULL,
    meaning text,
    example_chars text,
    CONSTRAINT radicals_pkey PRIMARY KEY (id),
    CONSTRAINT radicals_set_id_fkey FOREIGN KEY (set_id) REFERENCES radical_sets (id) ON DELETE CASCADE
);

CREATE TABLE search_history (
    id uuid NOT NULL DEFAULT (uuid_generate_v4()),
    user_id uuid NOT NULL,
    query character varying(200) NOT NULL,
    vocab_id uuid,
    searched_at timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT search_history_pkey PRIMARY KEY (id),
    CONSTRAINT search_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT search_history_vocab_id_fkey FOREIGN KEY (vocab_id) REFERENCES vocabulary (id)
);

CREATE TABLE user_word_progress (
    user_id uuid NOT NULL,
    vocab_id uuid NOT NULL,
    status character varying(20) NOT NULL DEFAULT ('learning'::character varying),
    review_count smallint NOT NULL,
    last_reviewed timestamp with time zone NOT NULL DEFAULT (now()),
    CONSTRAINT user_word_progress_pkey PRIMARY KEY (user_id, vocab_id),
    CONSTRAINT user_word_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT user_word_progress_vocab_id_fkey FOREIGN KEY (vocab_id) REFERENCES vocabulary (id) ON DELETE CASCADE
);
COMMENT ON TABLE user_word_progress IS 'Luu l?ch s? h?c t?p/tra c?u c?a t?ng t? v?ng ri�ng bi?t';

CREATE INDEX idx_challenge_words_lesson ON challenge_words (lesson_id, sort_order);

CREATE INDEX idx_docs_category ON documents (category_id);

CREATE INDEX idx_hanzi_lesson ON hanzi_cards (lesson_id, sort_order);

CREATE INDEX "IX_import_jobs_category_id" ON import_jobs (category_id);

CREATE INDEX "IX_import_jobs_uploaded_by" ON import_jobs (uploaded_by);

CREATE UNIQUE INDEX lesson_categories_slug_key ON lesson_categories (slug);

CREATE INDEX idx_lessons_category ON lessons (category_id);

CREATE INDEX idx_lessons_filename ON lessons (filename);

CREATE INDEX idx_media_owner ON media_files (owner_type, owner_id);

CREATE INDEX "IX_media_files_uploaded_by" ON media_files (uploaded_by);

CREATE UNIQUE INDEX permissions_code_key ON permissions (code);

CREATE INDEX idx_quiz_options_question ON quiz_options (question_id, sort_order);

CREATE INDEX idx_quiz_lesson ON quiz_questions (lesson_id, sort_order);

CREATE INDEX "IX_radical_sets_lesson_id" ON radical_sets (lesson_id);

CREATE UNIQUE INDEX radical_sets_set_number_key ON radical_sets (set_number);

CREATE INDEX "IX_radicals_set_id" ON radicals (set_id);

CREATE INDEX idx_role_permissions_role ON role_permissions (role_id);

CREATE INDEX "IX_role_permissions_permission_id" ON role_permissions (permission_id);

CREATE UNIQUE INDEX roles_code_key ON roles (code);

CREATE INDEX idx_search_user ON search_history (user_id, searched_at DESC);

CREATE INDEX "IX_search_history_vocab_id" ON search_history (vocab_id);

CREATE INDEX idx_progress_completed ON user_progress (user_id, completed);

CREATE INDEX idx_progress_lesson ON user_progress (lesson_id);

CREATE INDEX idx_progress_user ON user_progress (user_id);

CREATE UNIQUE INDEX user_progress_user_id_lesson_id_key ON user_progress (user_id, lesson_id);

CREATE INDEX idx_user_roles_user ON user_roles (user_id);

CREATE INDEX "IX_user_roles_role_id" ON user_roles (role_id);

CREATE INDEX idx_sessions_expires ON user_sessions (expires_at);

CREATE INDEX idx_sessions_token ON user_sessions (refresh_token);

CREATE INDEX idx_sessions_user ON user_sessions (user_id);

CREATE UNIQUE INDEX user_sessions_refresh_token_key ON user_sessions (refresh_token);

CREATE INDEX "IX_user_word_progress_vocab_id" ON user_word_progress (vocab_id);

CREATE UNIQUE INDEX users_email_key ON users (email);

CREATE UNIQUE INDEX users_username_key ON users (username);

CREATE INDEX idx_vocab_lesson ON vocabulary (lesson_id, sort_order);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260425011229_Baseline', '10.0.5');

COMMIT;

